### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by lelit**

### CODE REVIEW

**Comment by lelit** [comment]
Too bad I missed the 2.0.0 release...

**Comment by tisto** [comment]
@lelit did you run bin/updatetranslations on your PR?

**Comment by lelit** [comment]
No, as I didn't notice any change in the pot file since I did the translation, in 2020.

Should I do that?

**Comment by tisto** [comment]
@lelit just to be sure we are up-to-date. Please add a changelog entry. For the future it is easier for me to handle when you create a branch instead of a fork.

**Comment by lelit** [comment]
I added the changelog entry, and updated the PO files as indicated.

**Comment by mauritsvanrees** [comment]
I have released this in version 2.0.1.  Grazie! :-)

**Pull request merged**
